//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mingle.UC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mingle.UC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address with same title already exist.
        /// </summary>
        internal static string AddressWithSameTitleAlreadyExist {
            get {
                return ResourceManager.GetString("AddressWithSameTitleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact already exist with same details.
        /// </summary>
        internal static string ContactAlreadyExistWithSameDetails {
            get {
                return ResourceManager.GetString("ContactAlreadyExistWithSameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date with same title already exist.
        /// </summary>
        internal static string DateWithSameTitleAlreadyExist {
            get {
                return ResourceManager.GetString("DateWithSameTitleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to delete this party?.
        /// </summary>
        internal static string DeleteParty {
            get {
                return ResourceManager.GetString("DeleteParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department already exist for this party.
        /// </summary>
        internal static string DepartmentAlreadyExistForThisParty {
            get {
                return ResourceManager.GetString("DepartmentAlreadyExistForThisParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department cannot be blank.
        /// </summary>
        internal static string DepartmentCannotBeBlank {
            get {
                return ResourceManager.GetString("DepartmentCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email with same title already exist.
        /// </summary>
        internal static string EmailWithSameTitleAlreadyExist {
            get {
                return ResourceManager.GetString("EmailWithSameTitleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant messenger with same details already exist.
        /// </summary>
        internal static string ImWithSameDetailsAlreadyExist {
            get {
                return ResourceManager.GetString("ImWithSameDetailsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language already exist for this party.
        /// </summary>
        internal static string LanguageAlreadyExistForThisParty {
            get {
                return ResourceManager.GetString("LanguageAlreadyExistForThisParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language cannot be blank.
        /// </summary>
        internal static string LanguageCannotBeBlank {
            get {
                return ResourceManager.GetString("LanguageCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature of contact already exist for this party.
        /// </summary>
        internal static string NatureOfContactAlreadyExistForThisParty {
            get {
                return ResourceManager.GetString("NatureOfContactAlreadyExistForThisParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature of contact cannot be blank.
        /// </summary>
        internal static string NatureOfContactCannotBeBlank {
            get {
                return ResourceManager.GetString("NatureOfContactCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number with same title already exist.
        /// </summary>
        internal static string NumberWithSameTitleAlreadyExist {
            get {
                return ResourceManager.GetString("NumberWithSameTitleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party saved successfully.
        /// </summary>
        internal static string PartySavedSuccessfully {
            get {
                return ResourceManager.GetString("PartySavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession already exist for this party.
        /// </summary>
        internal static string ProfessionAlreadyExistForThisParty {
            get {
                return ResourceManager.GetString("ProfessionAlreadyExistForThisParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession cannot be blank.
        /// </summary>
        internal static string ProfessionCannotBeBlank {
            get {
                return ResourceManager.GetString("ProfessionCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property with same title already exist.
        /// </summary>
        internal static string PropertyWithSameTitleAlreadyExist {
            get {
                return ResourceManager.GetString("PropertyWithSameTitleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation already exist with same details.
        /// </summary>
        internal static string RelationAlreadyExistWithSameDetails {
            get {
                return ResourceManager.GetString("RelationAlreadyExistWithSameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website with same title already exist.
        /// </summary>
        internal static string WebsiteWithSameTitleAlreadyExist {
            get {
                return ResourceManager.GetString("WebsiteWithSameTitleAlreadyExist", resourceCulture);
            }
        }
    }
}
