//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergy.UC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Synergy.UC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ALARM {
            get {
                return ResourceManager.GetStream("ALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already loggedIn at other machine.
        ///Do you wish to force log off the other?.
        /// </summary>
        internal static string AlreadyLoggedInForceLogOff {
            get {
                return ResourceManager.GetString("AlreadyLoggedInForceLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment already exist.
        /// </summary>
        internal static string AttachmentAlreadyExist {
            get {
                return ResourceManager.GetString("AttachmentAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment name cannot be empty.
        /// </summary>
        internal static string AttachmentNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("AttachmentNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment {0} cannot be empty.
        /// </summary>
        internal static string AttachmentPathCannotBeEmpty {
            get {
                return ResourceManager.GetString("AttachmentPathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to unexpected end of the program,
        ///Task #{0} was unclosed.
        ///Please specify the duration you worked
        ///on Task #{0} on previous login
        ///
        ///NOTE: Closing without entering will
        ///consider current time as total duration.
        /// </summary>
        internal static string CurrentTaskPreviousDuration {
            get {
                return ResourceManager.GetString("CurrentTaskPreviousDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration exceeding current time, setting current time as stop time.
        /// </summary>
        internal static string ExceedingCurrentTaskDuration {
            get {
                return ResourceManager.GetString("ExceedingCurrentTaskDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current task.
        /// </summary>
        internal static string NoCurrentTask {
            get {
                return ResourceManager.GetString("NoCurrentTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks found for the search criteria 
        ///
        ///&apos;{0}&apos;.
        /// </summary>
        internal static string NoTasksFoundForTheSearchCriteria {
            get {
                return ResourceManager.GetString("NoTasksFoundForTheSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not tasks found with word &quot;{0}&quot;.
        /// </summary>
        internal static string NotTasksFound {
            get {
                return ResourceManager.GetString("NotTasksFound", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Pinned {
            get {
                object obj = ResourceManager.GetObject("Pinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set task done.
        /// </summary>
        internal static string SetTaskDone {
            get {
                return ResourceManager.GetString("SetTaskDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Task #{0} not found
        ///	      or
        ///You are not privileged for the task.
        /// </summary>
        internal static string TaskNotFound {
            get {
                return ResourceManager.GetString("TaskNotFound", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UnPinned {
            get {
                object obj = ResourceManager.GetObject("UnPinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to cancel this task.
        /// </summary>
        internal static string WantToCancelTask {
            get {
                return ResourceManager.GetString("WantToCancelTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the attachment.
        /// </summary>
        internal static string WantToRemoveAttachment {
            get {
                return ResourceManager.GetString("WantToRemoveAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to reopen closed task.
        /// </summary>
        internal static string WantToReopenTask {
            get {
                return ResourceManager.GetString("WantToReopenTask", resourceCulture);
            }
        }
    }
}
