//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foresight.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foresight.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting updation.
        /// </summary>
        internal static string AbortingUpdation {
            get {
                return ResourceManager.GetString("AbortingUpdation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to abort the updation?.
        /// </summary>
        internal static string AreYouSureToAbortUpdation {
            get {
                return ResourceManager.GetString("AreYouSureToAbortUpdation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This company period is imported. Are you sure to delete?
        ///
        ///WARNING: Deleting company period will delete imported data..
        /// </summary>
        internal static string DeleteImportedCompanyPeriod {
            get {
                return ResourceManager.GetString("DeleteImportedCompanyPeriod", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Foresight {
            get {
                object obj = ResourceManager.GetObject("Foresight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForesightLogo {
            get {
                object obj = ResourceManager.GetObject("ForesightLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForesightSplash {
            get {
                object obj = ResourceManager.GetObject("ForesightSplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting update....
        /// </summary>
        internal static string StartingUpdating {
            get {
                return ResourceManager.GetString("StartingUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updation aborted..
        /// </summary>
        internal static string UpdateAborted {
            get {
                return ResourceManager.GetString("UpdateAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updation failed..
        /// </summary>
        internal static string UpdateDataFailed {
            get {
                return ResourceManager.GetString("UpdateDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updation was successfull..
        /// </summary>
        internal static string UpdateDataSuccessfull {
            get {
                return ResourceManager.GetString("UpdateDataSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updation is in progress....
        /// </summary>
        internal static string UpdateInProgress {
            get {
                return ResourceManager.GetString("UpdateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started at: {0}.
        /// </summary>
        internal static string UpdateStartedAt {
            get {
                return ResourceManager.GetString("UpdateStartedAt", resourceCulture);
            }
        }
    }
}
