//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferry.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferry.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import data from {0}.
        ///
        ///Possible source data path is in use by another.
        ///
        ///Note: {1}.
        /// </summary>
        internal static string CouldNotImportDataSourceIsInUse {
            get {
                return ResourceManager.GetString("CouldNotImportDataSourceIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger Group File: {0} not found.
        /// </summary>
        internal static string GeneralLedgerGroupFileNotFound {
            get {
                return ResourceManager.GetString("GeneralLedgerGroupFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified importer {0} not supported.
        /// </summary>
        internal static string ImporterNotSupported {
            get {
                return ResourceManager.GetString("ImporterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No import provider found for this data path
        ///
        ///Make sure following files exists:
        ///
        ///For EASY: check CO_GRP.DBF and CO_FILE.DBF
        ///For MCS: check MNCOM.DBF and MNGRP.DBF
        ///For TCS: check RPCOM.DBF and RPGRP.DBF.
        /// </summary>
        internal static string ImportProviderFilesNotFound {
            get {
                return ResourceManager.GetString("ImportProviderFilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified source data folder {0} is invalid..
        /// </summary>
        internal static string InvalidSourceDataPath {
            get {
                return ResourceManager.GetString("InvalidSourceDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified source database provider {0} not supported.
        /// </summary>
        internal static string SourceDatabaseProviderNotSupported {
            get {
                return ResourceManager.GetString("SourceDatabaseProviderNotSupported", resourceCulture);
            }
        }
    }
}
