//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Insight.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account aready exist.
        /// </summary>
        internal static string AccountAlreadyExist {
            get {
                return ResourceManager.GetString("AccountAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name cannot be empty.
        /// </summary>
        internal static string AccountNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("AccountNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account to credit cannot be empty.
        /// </summary>
        internal static string AccountToCreditCannotBeEmpty {
            get {
                return ResourceManager.GetString("AccountToCreditCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account to debit cannot be empty.
        /// </summary>
        internal static string AccountToDebitCannotBeEmpty {
            get {
                return ResourceManager.GetString("AccountToDebitCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount cannot be zero.
        /// </summary>
        internal static string AmountCannotBeZero {
            get {
                return ResourceManager.GetString("AmountCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank details cannot be empty.
        /// </summary>
        internal static string BankDetailsCannotBeEmpty {
            get {
                return ResourceManager.GetString("BankDetailsCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill term code cannot be empty.
        /// </summary>
        internal static string BillTermCodeCannotBeEmpty {
            get {
                return ResourceManager.GetString("BillTermCodeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of account already exist.
        /// </summary>
        internal static string ChartOfAccountAlreadyExist {
            get {
                return ResourceManager.GetString("ChartOfAccountAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of account name cannot be empty.
        /// </summary>
        internal static string ChartOfAccountNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ChartOfAccountNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque no. cannot be empty.
        /// </summary>
        internal static string ChequeNrCannotBeEmpty {
            get {
                return ResourceManager.GetString("ChequeNrCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company already exist.
        /// </summary>
        internal static string CompanyAlreadyExist {
            get {
                return ResourceManager.GetString("CompanyAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company cannot be empty.
        /// </summary>
        internal static string CompanyCannotBeEmpty {
            get {
                return ResourceManager.GetString("CompanyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name cannot be empty.
        /// </summary>
        internal static string CompanyNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("CompanyNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company period already exist.
        /// </summary>
        internal static string CompanyPeriodAlreadyExist {
            get {
                return ResourceManager.GetString("CompanyPeriodAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company period cannot be empty.
        /// </summary>
        internal static string CompanyPeriodCannotBeEmpty {
            get {
                return ResourceManager.GetString("CompanyPeriodCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daybook already exist.
        /// </summary>
        internal static string DaybookAlreadyExist {
            get {
                return ResourceManager.GetString("DaybookAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daybook name cannot be empty.
        /// </summary>
        internal static string DaybookNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("DaybookNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be empty.
        /// </summary>
        internal static string DescriptionCannotBeEmpty {
            get {
                return ResourceManager.GetString("DescriptionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal date period already exist.
        /// </summary>
        internal static string FiscalDatePeriodAlreadyExist {
            get {
                return ResourceManager.GetString("FiscalDatePeriodAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal date period name cannot be empty.
        /// </summary>
        internal static string FiscalDatePeriodNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("FiscalDatePeriodNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item cannot be empty.
        /// </summary>
        internal static string ItemCannotBeEmpty {
            get {
                return ResourceManager.GetString("ItemCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item category name connot be empty.
        /// </summary>
        internal static string ItemCategoryNameConnotBeEmpty {
            get {
                return ResourceManager.GetString("ItemCategoryNameConnotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item group name cannot be empty.
        /// </summary>
        internal static string ItemGroupNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ItemGroupNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name cannot be empty.
        /// </summary>
        internal static string ItemNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ItemNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party cannot be empty.
        /// </summary>
        internal static string PartyCannotBeEmpty {
            get {
                return ResourceManager.GetString("PartyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period cannot be empty.
        /// </summary>
        internal static string PeriodCannotBeEmpty {
            get {
                return ResourceManager.GetString("PeriodCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity cannot be zero.
        /// </summary>
        internal static string QuantityCannotBeZero {
            get {
                return ResourceManager.GetString("QuantityCannotBeZero", resourceCulture);
            }
        }
    }
}
